version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
