server:
  port: 8080

spring:
  application:
    name: product-service
  data:
    mongodb:
      authentication-database: admin
      password: password
      username: admin
      uri: mongodb://localhost:27017/product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka